#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# run_e2e.sh - end-to-end CLI tests for bun_parser.
#
# Reads tests/fixtures/expectations.tsv (generated by make_fixtures.py) and
# for every listed fixture, runs ./bun_parser on it and checks that the
# exit code matches the expectation.
#
# Does NOT check output text - that is the domain of the libcheck unit tests
# and (later) golden-file tests once the output format is pinned down.
#
# Author: Group 22, Member 4.
# -----------------------------------------------------------------------------

set -u
set -o pipefail

PROG=./bun_parser
EXPECT_FILE=tests/fixtures/expectations.tsv
FIX_DIR=tests/fixtures

if [[ ! -x "$PROG" ]]; then
  echo "ERROR: $PROG not found or not executable. Run 'make all' first." >&2
  exit 99
fi
if [[ ! -f "$EXPECT_FILE" ]]; then
  echo "ERROR: $EXPECT_FILE not found. Run 'make fixtures' first." >&2
  exit 99
fi

pass=0
fail=0
failed_cases=()

# Process expectations file line by line, skipping blank / comment lines.
while IFS=$'\t' read -r fixture expected; do
  case "$fixture" in
    ''|\#*) continue ;;
  esac
  path="$FIX_DIR/$fixture"
  if [[ ! -f "$path" ]]; then
    echo "SKIP  $fixture  (fixture missing)"
    continue
  fi

  # Invoke bun_parser; capture only the exit code. Suppress stdout/stderr to
  # keep the E2E summary readable; developers can run the binary manually to
  # see output.
  set +e
  "$PROG" "$path" >/dev/null 2>&1
  got=$?
  set -e

  if [[ "$got" == "$expected" ]]; then
    pass=$((pass + 1))
    printf "PASS  %-50s exit=%s\n" "$fixture" "$got"
  else
    fail=$((fail + 1))
    failed_cases+=("$fixture (expected $expected, got $got)")
    printf "FAIL  %-50s exit=%s (expected %s)\n" "$fixture" "$got" "$expected"
  fi
done < "$EXPECT_FILE"

echo
echo "E2E summary: $pass passed, $fail failed"
if (( fail > 0 )); then
  echo "Failed cases:"
  for f in "${failed_cases[@]}"; do
    echo "  - $f"
  done
  exit 1
fi
exit 0
